FROM golang:1.17-alpine as builder
WORKDIR $GOPATH/src/go.k6.io/k6
# RUN CGO_ENABLED=0 go install -a -trimpath -ldflags "-s -w -X go.k6.io/k6/lib/consts.VersionDetails=$(date -u +"%FT%T%z")/$(git describe --always --long --dirty)"
ADD . .
RUN apk --no-cache add git
RUN CGO_ENABLED=0 go install go.k6.io/xk6/cmd/xk6@latest
RUN CGO_ENABLED=0 xk6 build --output /k6  --with github.com/henrikrexed/xk6-output-dynatrace=. --with github.com/grafana/xk6-distributed-tracing@latest


# COPY ./tests ./tests

FROM loadimpact/k6:latest
COPY --chown=root:root ./loadgenerator.js ./loadgenerator.js
COPY --from=builder /k6 /usr/bin/k6
ENTRYPOINT ["k6","run","-o", "output-dynatrace" ,"./loadgenerator.js"]